# запуск:
# docker compose --profile system up -d
# docker compose --profile server up -d

version: '3.8'

name: kleck

services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8001:9000"
    restart: always
    profiles:
      - system
    volumes:
      - portainer_data_volume:/data
      - /var/run/docker.sock:/var/run/docker.sock

  webapp:
    image: docker-registry:5000/docker-example/webapp
    container_name: webapp
    hostname: webapp
    profiles:
      - server
    ports:
      - "80:80"

  python_service:
    image: docker-registry:5000/docker-example/python_service
    container_name: python_service
    hostname: python_service
    privileged: true
    profiles:
      - server
    ports:
      - "8010:8000"
    volumes:
      - /dev:/dev
      - .:/root/code

volumes:
  portainer_data_volume:
    name: portainer_data_volume
