# запуск:
# docker compose --profile system up -d
# docker compose --profile server up -d

version: '3.8'

name: kleck

services:

  docker_registry:
    image: registry:2.7
    container_name: docker_registry
    ports:
      - "5000:5000"
    profiles:
      - system
    restart: always
    volumes:
      - docker_registry_volume:/var/lib/registry
      - ./docker-registry-config.yml:/etc/docker/registry/config.yml

  docker_registry_ui:
    image: joxit/docker-registry-ui:latest
    container_name: docker_registry_ui
    depends_on:
      - docker_registry
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - REGISTRY_URL=http://target:5000
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
    ports:
      - "8000:80"
    profiles:
      - system
    restart: always

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8001:9000"
    restart: always
    profiles:
      - system
    volumes:
      - portainer_data_volume:/data
      - /var/run/docker.sock:/var/run/docker.sock

  webapp:
    image: target:5000/docker-example/webapp
    container_name: webapp
    hostname: webapp
    profiles:
      - server
    ports:
      - "80:80"

  python_service:
    image: target:5000/docker-example/python_service
    container_name: python_service
    hostname: python_service
    privileged: true
    profiles:
      - server
    ports:
      - "8010:8000"
    volumes:
      - /dev:/dev
      - .:/root/code

volumes:
  docker_registry_volume:
    name: docker_registry_volume
  portainer_data_volume:
    name: portainer_data_volume
